on: [push]

name: on-push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run install.sh
        shell: bash
        run: |
          ./install.sh
